### ISSUE TITLE
Trip with negative/zero animals

### ISSUE THREAD

**Issue by AlbanaJaha** [scg-unibe-ch/ese2017-team3#23]
**Summary**
You can create a trip with a negative amount of animals or zero animals.

**Steps to reproduce**
Click on _New Tour_ and fill out the form with valid data.
For the number of the animals enter a negative number or 0.
Then click on _Save_.

**Expected result**
Can not create the trip.

**Actual result**
The trip gets created and added to the list.

**Comment by rolshoven** [comment]
Should not happen anymore
