### ISSUE TITLE
Can not enter an address with special house number (e.g. 1A)

### ISSUE THREAD

**Issue by AlbanaJaha** [scg-unibe-ch/ese2017-team3#25]
**Summary**
You can not create a trip with special house number.

**Steps to reproduce**
Click on _New Tour_ and fill out the form with valid data.
For the house number enter e.g. 1A
Then click on _Save_.

**Expected result**
Can create trips with house numbers that contain letters.

**Actual result**
The trip gets created and added to the list.

**Comment by rolshoven** [comment]
Should now be possible
