### ISSUE TITLE
Can not log out or switch account

### ISSUE THREAD

**Issue by AlbanaJaha** [scg-unibe-ch/ese2017-team3#26]
**Summary**
There is no option to log out from the account.
If we go to the start page _http://localhost:8080_ we get an error.
The only way to log in with an other account is to go to the log in page _http://localhost:8080/login_
This happens when we log in as drivers or as the admin.

**Comment by rolshoven** [comment]
Users can now log out by clicking on the upper right _Log Out_ button/link.
