### ISSUE TITLE
Admin is only created after a registration of a driver

### ISSUE THREAD

**Issue by AlbanaJaha** [scg-unibe-ch/ese2017-team3#27]
**Summary**
If you start with an empty datdabase you can not log in as _admin_ with password _anitrans_.
The admin only gets created when you register a new driver.

The following code should be moved to another location.
https://github.com/scg-unibe-ch/ese2017-team3/blob/37769d6d023b5f733f57befc0998049a02367618/Source/src/main/java/spring/controller/UserController.java#L47-L50

**Comment by MadCatZz** [comment]
Created an Application runner, which is run on startup and checks, if there is a user with the username admin, if not, it's created.
