### ISSUE TITLE
There should be an address-class

### ISSUE THREAD

**Issue by Dasteme** [scg-unibe-ch/ese2017-team3#28]
The class Tour has too many attributes which should be in a separate class
called Address. The attributes are:
 - startPersonName, contactPersonName
 - startPersonSurname, contactPersonSurname
 - startAddress, destinationAddress
 - startAddressNumber, destinationAddressNumber
 - startZip, destinationZip
 - startCity, destinationCity

**Comment by MadCatZz** [comment]
I assume, creating two different Address objects, one containing the start address and one containing the destination address would make more sense?

**Comment by Dasteme** [comment]
Of course, that's what i meant.
Thank you for your comment.
I would name the attributes of the address-class like:
  - personName           for (startPersonName, contactPersonName)
  - personSurname      for (startPersonSurname, contactPersonSurname)
  - street                      for (startAddress, destinationAddress)
  - streetNumber         for (startAddressNumber, destinationAddressNumber)
  - city                          for (startCity, destinationCity)
  - zip                           for (startZip, destinationZip)

**Comment by MadCatZz** [comment]
Done, for follow-up issues open a new one, and assign it do me (MadCatZz)
