### ISSUE TITLE
Error validation on tourOverview for "time" and "date" doesn't work properly

### ISSUE THREAD

**Issue by Dasteme** [scg-unibe-ch/ese2017-team3#38]
- If the user tries to "delete" the entire time/date while editing a tour, he get's to the error-page
- If the user tries to enter an invalid date on tourOverview with a year which is too long,
   e.g. 10.08.2000000, he get's to the error-page

**Comment by MadCatZz** [comment]
Make Sure Dates/Times are in the future.

**Comment by MadCatZz** [comment]
Added a check if time/date lies in the future. Done.
