### ISSUE TITLE
replace 0 by "zip" placeholder when creating a new tour

### ISSUE THREAD

**Issue by MadCatZz** [scg-unibe-ch/ese2017-team3#42]

**Comment by Dasteme** [comment]
There are 3 approaches to do this:
 - Add a Zip label infront of the textbox
     -> 0 stays in the textbox
 - Replace th:field by  th:id, th:name, th:value  (and maybe th:errorclass)
     -> not very nice, maybe the bean-binding doesn't work anymore
 - Replace zip to string, add regex to it
     ->

**Comment by Dasteme** [comment]
There are 3 approaches to do this:

Add a Zip label infront of the textbox
-> 0 stays in the textbox
Replace th:field by th:id, th:name, th:value (and maybe th:errorclass)
-> not very nice, maybe the bean-binding doesn't work anymore
Replace zip to string, add regex to it
->

**Comment by Dasteme** [comment]
There are 3 approaches to do this:
- Add a Zip label in front of the textbox
    -> 0 stays in the textbox
- Replace th:field by th:id, th:name, th:value (and maybe th:errorclass)
    -> not very nice, maybe the bean-binding doesn't work anymore
- Replace zip to string, add regex to it
    -> it's not very nice to store zip as a string
